# -*- encoding: utf-8 -*-

CORREGIMIENTOS = (
	('ARROYOHONDO' , 'ARROYOHONDO'),
	('DAPA' , 'DAPA'),
	('MULALO' , 'MULALÓ'),
	('EL PEDREGAL' , 'EL PEDREGAL') ,
	('SAN MARCOS', 'SAN MARCOS'),
	('SANTA INES' , 'SANTA INÉS') ,
	('YUMBILLO','YUMBILLO'),
	('LA OLGA' , 'LA OLGA'),
	('LA BUITRERA' , 'LA BUITRERA'),
	('MONTAÑITAS' , 'MONTAÑITAS'),

)
VEREDAS = (
	('ARROYOHONDO' , 'ARROYOHONDO'),
	('XIXALOA' , 'XIXALOA'),
	('MIRAVALLE DAPA' , 'MIRAVALLE DAPA'),
	('ALTO DAPA' , 'ALTO DAPA'),
	('MEDIO DAPA' , 'MEDIO DAPA'),
	('PILAS DAPA' , 'PILAS DAPA'),
	('RINCON DAPA' , 'RINCÓN DAPA'),
	('EL PEDREGAL' , 'EL PEDREGAL'),
	('FILO Y LAGUNA' , 'FILO Y LAGUNA'),
	('MULALO ', 'MULALÓ '),
	('PLATANARES' , 'PLATANARES'),
	('PASO DE LA TORRE' , 'PASO DE LA TORRE'),
	('EL HIGUERON' , 'EL HIGUERÓN' ),
	('SAN MARCOS' , 'SAN MARCOS'),
	('MANGA VIEJA' , 'MANGA VIEJA'),
	('MIRAVALLE NORTE' , 'MIRAVALLE NORTE'),
	('SANTA INES' , 'SANTA INÉS'),
	('EL CHOCHO' , 'EL CHOCHO'),
	('TELECOM' , 'TELECOM'),
	('YUMBILLO', 'YUMBILLO'),
	('SALAZAR' , 'SALAZAR'),
	('LA OLGA' , 'LA OLGA'),
	('LA BUITRERA' , 'LA BUITRERA'),
	('MONTANITAS ' , 'MONTAÑITAS '),
	('SAN JOSE' , 'SAN JOSÉ'),
	('EL PLACER' , 'EL PLACER') ,


)
SUB_CUENCAS = (
	('YUMBILLO' , 'YUMBILLO'),
	('SANTA INES' , 'SANTA INÉS'),
	('LA BUITRERA' , 'LA BUITRERA'),
	('MULALO' , 'MULALÓ'),
	('LA PEREZ' , 'LA PEREZ'),

)

CUENCAS = (

	('YUMBO' , 'YUMBO'),
	('ARROYOHONDO' , 'ARROYOHONDO'),
	('CAUCA' , 'CAUCA'),
)
#################################################